[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AI/ML TACC Introduction"
authors = [{name = "Alexis Phan", email = "alexisphan@utexas.edu"}]
dynamic = ["version", "description"]