[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-ml-tacc-introduction"  # Replace '/' with '-'
authors = [{name = "Alexis Phan", email = "alexisphan@utexas.edu"}]
dynamic = ["version", "description"]
